/**********************************************\
* Course: Introduction to Security 
* Final Project
* Student: Xiaoxiao Yu
* E-mail: xiy38@pitt.edu
* Last modified: 2013/04/03
\**********************************************/

import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.Key;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Scanner;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;

public class RSABob {
	private static Key public_key;
	private static Key private_key;

	protected static void generate_key() throws NoSuchAlgorithmException {
		int mStrength = 1024; // key bit length
		SecureRandom mSecureRandom = new SecureRandom();

		KeyPairGenerator key_gen = KeyPairGenerator.getInstance("RSA");
		key_gen.initialize(mStrength, mSecureRandom);
		KeyPair keys = key_gen.generateKeyPair();
		public_key = (Key) keys.getPublic();
		private_key = (Key) keys.getPrivate();
	}

	protected static byte[] decrypt_func(byte[] msg, Cipher cipher)
			throws IllegalBlockSizeException, BadPaddingException, IOException {
		ByteArrayOutputStream byte_stream = new ByteArrayOutputStream();
		byte[] cache;
		int block_size = 128;
		int cnt = 0;

		while (cnt < msg.length) {
			if ((msg.length - cnt) >= block_size) {
				cache = cipher.doFinal(msg, cnt, block_size);
			} else {
				cache = cipher.doFinal(msg, cnt, msg.length - cnt);
			}
			byte_stream.write(cache, 0, cache.length);
			cnt += block_size;
		}

		byte[] decrypted_msg = byte_stream.toByteArray();
		byte_stream.close();
		return decrypted_msg;
	}

	public static void main(String[] args) throws Exception {
		int port = 7999;
		ServerSocket server = new ServerSocket(port);

		// Generate a RSA key.
		generate_key();
		System.out.println("Key generated.");

		// Store it in a file.
		FileOutputStream f_out = new FileOutputStream("RSAKeyFileBob.dat");
		ObjectOutputStream out = new ObjectOutputStream(f_out);
		out.writeObject(public_key);
		out.close();

		// Waiting for key sharing
		System.out.println("After all keys are saved in the files.");
		System.out.print("Press Enter to continue...");
		Scanner scanIn = new Scanner(System.in);
		scanIn.nextLine();
		scanIn.close();

		// Read the public key from the file generated by server.
		FileInputStream f_in = new FileInputStream("RSAKeyFileAlice.dat");
		ObjectInputStream in = new ObjectInputStream(f_in);
		Key public_key_Alice = (Key) in.readObject();

		// Use the key to decrypt the incoming message from socket s.
		Socket s = server.accept();
		ObjectInputStream is = new ObjectInputStream(s.getInputStream());
		byte[] enciphered_msg = (byte[]) is.readObject();
		is.close();
		s.close();

		// Decryption
		byte[] deciphered_msg;
		Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
		// - decipher by Bob's private key
		cipher.init(Cipher.DECRYPT_MODE, private_key);
		deciphered_msg = decrypt_func(enciphered_msg, cipher);
		// - decipher by Alice's public key
		cipher.init(Cipher.DECRYPT_MODE, public_key_Alice);
		deciphered_msg = decrypt_func(deciphered_msg, cipher);

		// print out
		// System.out.println(Arrays.toString(deciphered_msg));
		String message = new String(deciphered_msg, "UTF-8");
		System.out.println(message);
	}
}